name: Test Init Repos Script

on:
  workflow_dispatch:  # Manual trigger for testing

jobs:
  test-init-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run init_repos.py
      run: |
        echo "Running init_repos.py script..."
        python3 scripts/init_repos.py

    - name: List base_artifact directory
      run: |
        echo "Verifying cloned repositories..."
        ls -R base_artifact
