name: Basic Test Workflow

# Manual trigger
on:
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print Hello Message
        run: echo "Hello, Djowda Automation is working!"

      - name: List Files
        run: ls -la

      - name: Print Current Branch
        run: echo "Currently on branch: ${{ github.ref_name }}"
