name: Test Automation

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "🚀 Hello Djowda Automation World! Workflow is running fine."

      - name: List repo files
        run: ls -la

      - name: Print current branch
        run: echo "Current branch: ${{ github.ref }}"
